Update source to 1.14.5

diff --git a/hdf5/hl/fortran/src/Makefile.in b/hdf5/hl/fortran/src/Makefile.in
--- a/hdf5/hl/fortran/src/Makefile.in
+++ b/hdf5/hl/fortran/src/Makefile.in
@@ -115,11 +115,20 @@ host_triplet = @host@
 noinst_PROGRAMS = H5HL_buildiface$(EXEEXT)
 TESTS =
 
+# Splitter VFD currently can't be tested with the h5_fileaccess()
+# approach due to it trying to lock the same W/O file when two
+# files are created/opened with the same FAPL that has the VFD
+# set on it. When tested with the environment variable and a
+# default FAPL, the VFD appends "_wo" to the filename when the
+# W/O path isn't specified, which works for all the tests.
+# VFD_LIST += splitter
+
 # log VFD currently has file space allocation bugs
 # VFD_LIST += log
+
+# Not currently tested with VFD tests
+# VFD_LIST += onion
 @DIRECT_VFD_CONDITIONAL_TRUE@am__append_2 = direct
-@ROS3_VFD_CONDITIONAL_TRUE@am__append_3 = ros3
-@HDFS_VFD_CONDITIONAL_TRUE@am__append_4 = hdfs
 subdir = hl/fortran/src
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 am__aclocal_m4_deps = $(top_srcdir)/m4/aclocal_fc.m4 \
@@ -181,7 +190,7 @@ LTLIBRARIES = $(lib_LTLIBRARIES)
 libhdf5hl_fortran_la_DEPENDENCIES = $(LIBH5_HL) $(LIBH5F)
 am_libhdf5hl_fortran_la_OBJECTS = H5DSfc.lo H5LTfc.lo H5IMfc.lo \
 	H5IMcc.lo H5TBfc.lo H5DSff.lo H5LTff.lo H5TBff.lo H5IMff.lo \
-	H5LTff_gen.lo H5TBff_gen.lo
+	H5DOff.lo H5LTff_gen.lo H5TBff_gen.lo
 libhdf5hl_fortran_la_OBJECTS = $(am_libhdf5hl_fortran_la_OBJECTS)
 AM_V_lt = $(am__v_lt_@AM_V@)
 am__v_lt_ = $(am__v_lt_@AM_DEFAULT_V@)
@@ -484,7 +493,6 @@ CCDEPMODE = @CCDEPMODE@
 CC_VERSION = @CC_VERSION@
 CFLAGS = @CFLAGS@
 CLANG_SANITIZE_CHECKS = @CLANG_SANITIZE_CHECKS@
-CODESTACK = @CODESTACK@
 CONFIG_DATE = @CONFIG_DATE@
 CONFIG_MODE = @CONFIG_MODE@
 CONFIG_USER = @CONFIG_USER@
@@ -570,6 +578,7 @@ FCFLAGS_f90 = @FCFLAGS_f90@
 FCLIBS = @FCLIBS@
 FC_VERSION = @FC_VERSION@
 FGREP = @FGREP@
+FORTRAN_C_BOOL_IS_UNIQUE = @FORTRAN_C_BOOL_IS_UNIQUE@
 FORTRAN_C_LONG_DOUBLE_IS_UNIQUE = @FORTRAN_C_LONG_DOUBLE_IS_UNIQUE@
 FORTRAN_HAVE_C_LONG_DOUBLE = @FORTRAN_HAVE_C_LONG_DOUBLE@
 FSEARCH_DIRS = @FSEARCH_DIRS@
@@ -599,10 +608,13 @@ H5_UTILS_TEST_BUILDDIR = @H5_UTILS_TEST_BUILDDIR@
 H5_VERSION = @H5_VERSION@
 HADDR_T = @HADDR_T@
 HAVE_Fortran_INTEGER_SIZEOF_16 = @HAVE_Fortran_INTEGER_SIZEOF_16@
+HAVE_ISO_FORTRAN_ENV = @HAVE_ISO_FORTRAN_ENV@
 HAVE_LIBHDFS = @HAVE_LIBHDFS@
 HAVE_MERCURY = @HAVE_MERCURY@
 HAVE_PTHREAD = @HAVE_PTHREAD@
+HAVE__FLOAT16 = @HAVE__FLOAT16@
 HDF5_DOXYGEN = @HDF5_DOXYGEN@
+HDF5_DOXY_WARNINGS = @HDF5_DOXY_WARNINGS@
 HDF5_HL = @HDF5_HL@
 HDF5_HL_GIF_TOOLS = @HDF5_HL_GIF_TOOLS@
 HDF5_HL_TOOLS = @HDF5_HL_TOOLS@
@@ -650,13 +662,13 @@ LL_PATH = @LL_PATH@
 LN_S = @LN_S@
 LTLIBOBJS = @LTLIBOBJS@
 LT_STATIC_EXEC = @LT_STATIC_EXEC@
-LT_SYS_LIBRARY_PATH = @LT_SYS_LIBRARY_PATH@
 MAINT = @MAINT@
 MAKEINFO = @MAKEINFO@
 MANIFEST_TOOL = @MANIFEST_TOOL@
 MAP_API = @MAP_API@
 MIRROR_VFD = @MIRROR_VFD@
 MKDIR_P = @MKDIR_P@
+MPI_LOGICAL_KIND = @MPI_LOGICAL_KIND@
 NM = @NM@
 NMEDIT = @NMEDIT@
 OBJDUMP = @OBJDUMP@
@@ -685,6 +697,7 @@ PAC_FORTRAN_NATIVE_INTEGER_SIZEOF = @PAC_FORTRAN_NATIVE_INTEGER_SIZEOF@
 PAC_FORTRAN_NATIVE_REAL_KIND = @PAC_FORTRAN_NATIVE_REAL_KIND@
 PAC_FORTRAN_NATIVE_REAL_SIZEOF = @PAC_FORTRAN_NATIVE_REAL_SIZEOF@
 PAC_FORTRAN_NUM_INTEGER_KINDS = @PAC_FORTRAN_NUM_INTEGER_KINDS@
+PAC_MPI_LOGICAL_KIND = @PAC_MPI_LOGICAL_KIND@
 PARALLEL = @PARALLEL@
 PARALLEL_FILTERED_WRITES = @PARALLEL_FILTERED_WRITES@
 PARALLEL_TOOLS = @PARALLEL_TOOLS@
@@ -702,6 +715,7 @@ SEARCH = @SEARCH@
 SED = @SED@
 SET_MAKE = @SET_MAKE@
 SHELL = @SHELL@
+SHOW_ALL_WARNINGS = @SHOW_ALL_WARNINGS@
 SIZE_T = @SIZE_T@
 STATIC_EXEC = @STATIC_EXEC@
 STATIC_SHARED = @STATIC_SHARED@
@@ -843,29 +857,29 @@ CHECK_CLEANFILES = *.chkexe *.chklog
 # See libtool versioning documentation online.
 # After making changes, run bin/reconfigure to update other configure related
 # files like Makefile.in.
-LT_VERS_INTERFACE = 312
-LT_VERS_AGE = 2
+LT_VERS_INTERFACE = 315
 LT_VERS_REVISION = 0
+LT_VERS_AGE = 5
 LT_CXX_VERS_INTERFACE = 310
-LT_CXX_VERS_REVISION = 2
+LT_CXX_VERS_REVISION = 5
 LT_CXX_VERS_AGE = 0
-LT_F_VERS_INTERFACE = 311
+LT_F_VERS_INTERFACE = 313
 LT_F_VERS_REVISION = 1
-LT_F_VERS_AGE = 1
+LT_F_VERS_AGE = 3
 LT_HL_VERS_INTERFACE = 310
-LT_HL_VERS_REVISION = 2
+LT_HL_VERS_REVISION = 5
 LT_HL_VERS_AGE = 0
 LT_HL_CXX_VERS_INTERFACE = 310
-LT_HL_CXX_VERS_REVISION = 2
+LT_HL_CXX_VERS_REVISION = 5
 LT_HL_CXX_VERS_AGE = 0
 LT_HL_F_VERS_INTERFACE = 310
-LT_HL_F_VERS_REVISION = 2
+LT_HL_F_VERS_REVISION = 5
 LT_HL_F_VERS_AGE = 0
 LT_JAVA_VERS_INTERFACE = 310
-LT_JAVA_VERS_REVISION = 2
+LT_JAVA_VERS_REVISION = 5
 LT_JAVA_VERS_AGE = 0
 LT_TOOLS_VERS_INTERFACE = 310
-LT_TOOLS_VERS_REVISION = 2
+LT_TOOLS_VERS_REVISION = 5
 LT_TOOLS_VERS_AGE = 0
 
 # Our main target, the high-level fortran library
@@ -881,7 +895,7 @@ libhdf5hl_fortran_la_LDFLAGS = -version-info $(LT_HL_F_VERS_INTERFACE):$(LT_HL_F
 
 # List sources to include in the HDF5 HL Fortran library.
 libhdf5hl_fortran_la_SOURCES = H5DSfc.c H5LTfc.c H5IMfc.c H5IMcc.c H5TBfc.c \
-	H5DSff.F90 H5LTff.F90 H5TBff.F90 H5IMff.F90 H5LTff_gen.F90 H5TBff_gen.F90
+	H5DSff.F90 H5LTff.F90 H5TBff.F90 H5IMff.F90 H5DOff.F90 H5LTff_gen.F90 H5TBff_gen.F90
 
 
 # HDF5 HL Fortran library depends on HDF5 Library.
@@ -913,8 +927,8 @@ TEST_PROG_CHKEXE = $(TEST_PROG:=.chkexe_)
 TEST_PROG_PARA_CHKEXE = $(TEST_PROG_PARA:=.chkexe_)
 TEST_SCRIPT_CHKSH = $(TEST_SCRIPT:=.chkexe_)
 TEST_SCRIPT_PARA_CHKSH = $(TEST_SCRIPT_PARA:=.chkexe_)
-VFD_LIST = sec2 stdio core core_paged split multi family splitter \
-	$(am__append_2) $(am__append_3) $(am__append_4)
+VFD_LIST = sec2 stdio core core_paged split multi family \
+	$(am__append_2)
 
 # Test with just the native connector, with a single pass-through connector
 # and with a doubly-stacked pass-through.
@@ -1504,6 +1518,7 @@ H5DSff.lo:          $(srcdir)/H5DSff.F90
 H5LTff.lo:          $(srcdir)/H5LTff.F90
 H5IMff.lo:          $(srcdir)/H5IMff.F90
 H5TBff.lo:          $(srcdir)/H5TBff.F90
+H5DOff.lo:          $(srcdir)/H5DOff.F90
 H5LTff_gen.lo:      H5LTff.lo H5LTff_gen.F90
 H5TBff_gen.lo:      H5TBff.lo H5LTff_gen.F90 H5TBff_gen.F90
 
@@ -1633,15 +1648,15 @@ $(TEST_PROG_CHKEXE) $(TEST_PROG_PARA_CHKEXE) dummy.chkexe_:
                 if test -n "$(HDF5_VOL_CONNECTOR)"; then \
                   echo "VOL connector: $(HDF5_VOL_CONNECTOR)" | tee -a $${log}; \
                 fi; \
-                if test -n "$(HDF5_DRIVER)"; then \
-                  echo "Virtual file driver (VFD): $(HDF5_DRIVER)" | tee -a $${log}; \
+                if test -n "$(HDF5_TEST_DRIVER)"; then \
+                  echo "Virtual file driver (VFD): $(HDF5_TEST_DRIVER)" | tee -a $${log}; \
                 fi; \
               else \
                 if test -n "$(HDF5_VOL_CONNECTOR)"; then \
                   echo "VOL connector: $(HDF5_VOL_CONNECTOR)" >> $${log}; \
                 fi; \
-                if test -n "$(HDF5_DRIVER)"; then \
-                  echo "Virtual file driver (VFD): $(HDF5_DRIVER)" >> $${log}; \
+                if test -n "$(HDF5_TEST_DRIVER)"; then \
+                  echo "Virtual file driver (VFD): $(HDF5_TEST_DRIVER)" >> $${log}; \
                 fi; \
               fi; \
               if test -n "$(REALTIMEOUTPUT)"; then \
@@ -1758,20 +1773,23 @@ build-check-p: $(LIB) $(PROGS) $(chk_TESTS)
 @MIRROR_VFD_CONDITIONAL_TRUE@  # Mirror VFD needs network configuration, etc. and isn't easy to set
 @MIRROR_VFD_CONDITIONAL_TRUE@  # reasonable defaults for that info.
 @MIRROR_VFD_CONDITIONAL_TRUE@  # VFD_LIST += mirror
-@SUBFILING_VFD_CONDITIONAL_TRUE@  # Several VFD tests fail with Subfiling since it
-@SUBFILING_VFD_CONDITIONAL_TRUE@  # doesn't currently support collective I/O
+@ROS3_VFD_CONDITIONAL_TRUE@  # This would require a custom test suite
+@ROS3_VFD_CONDITIONAL_TRUE@  # VFD_LIST += ros3
+@HDFS_VFD_CONDITIONAL_TRUE@  # This would require a custom test suite
+@HDFS_VFD_CONDITIONAL_TRUE@  # VFD_LIST += hdfs
+@SUBFILING_VFD_CONDITIONAL_TRUE@  # Subfiling has a few VFD test failures to be resolved
 @SUBFILING_VFD_CONDITIONAL_TRUE@  # VFD_LIST += subfiling
 
 # Run test with different Virtual File Driver
 check-vfd: $(LIB) $(PROGS) $(chk_TESTS)
-	@for vfd in $(VFD_LIST) dummy; do                                     \
-	    if test $$vfd != dummy; then                                      \
-	        echo "============================";                          \
-	        echo "Testing Virtual File Driver $$vfd";                     \
-	        echo "============================";                          \
-	        $(MAKE) $(AM_MAKEFLAGS) check-clean || exit 1;                \
-	        HDF5_DRIVER=$$vfd $(MAKE) $(AM_MAKEFLAGS) check || exit 1;    \
-	    fi;                                                               \
+	@for vfd in $(VFD_LIST) dummy; do                                          \
+	    if test $$vfd != dummy; then                                           \
+	        echo "============================";                               \
+	        echo "Testing Virtual File Driver $$vfd";                          \
+	        echo "============================";                               \
+	        $(MAKE) $(AM_MAKEFLAGS) check-clean || exit 1;                     \
+	        HDF5_TEST_DRIVER=$$vfd $(MAKE) $(AM_MAKEFLAGS) check || exit 1;    \
+	    fi;                                                                    \
 	done
 
 # Run test with different passthrough Virtual Object Layer Connector
diff --git a/hdf5/tools/test/h5stat/testh5stat.sh.in b/hdf5/tools/test/h5stat/testh5stat.sh.in
--- a/hdf5/tools/test/h5stat/testh5stat.sh.in
+++ b/hdf5/tools/test/h5stat/testh5stat.sh.in
@@ -33,25 +33,26 @@ CP='cp'
 DIRNAME='dirname'
 LS='ls'
 AWK='awk'
+GREP='grep'
 
 nerrors=0
 verbose=yes
 
 # source dirs
 SRC_TOOLS="$srcdir/../.."
-SRC_TOOLS_TESTFILES="$SRC_TOOLS/testfiles"
 
 # testfiles source dirs for tools
-SRC_H5LS_TESTFILES="$SRC_TOOLS_TESTFILES"
-SRC_H5DUMP_TESTFILES="$SRC_TOOLS_TESTFILES"
+SRC_H5LS_TESTFILES="$SRC_TOOLS/test/h5ls/testfiles"
+SRC_H5DUMP_TESTFILES="$SRC_TOOLS/test/h5dump/testfiles"
 SRC_H5DIFF_TESTFILES="$SRC_TOOLS/test/h5diff/testfiles"
 SRC_H5COPY_TESTFILES="$SRC_TOOLS/test/h5copy/testfiles"
 SRC_H5REPACK_TESTFILES="$SRC_TOOLS/test/h5repack/testfiles"
 SRC_H5JAM_TESTFILES="$SRC_TOOLS/test/h5jam/testfiles"
 SRC_H5STAT_TESTFILES="$SRC_TOOLS/test/h5stat/testfiles"
 SRC_H5IMPORT_TESTFILES="$SRC_TOOLS/test/h5import/testfiles"
+SRC_H5STAT_OUTFILES="$SRC_TOOLS/test/h5stat/expected"
 
-TESTDIR=./testfiles
+TESTDIR=./tmp
 test -d $TESTDIR || mkdir $TESTDIR
 
 ######################################################################
@@ -74,56 +75,45 @@ $SRC_H5STAT_TESTFILES/h5stat_idx.h5
 $SRC_H5STAT_TESTFILES/h5stat_threshold.h5
 "
 
-LIST_ERR_TEST_FILES="
-$SRC_H5STAT_TESTFILES/h5stat_err_refcount.err
-$SRC_H5STAT_TESTFILES/h5stat_err_old_layout.err
-$SRC_H5STAT_TESTFILES/h5stat_err_old_fill.err
-$SRC_H5STAT_TESTFILES/h5stat_err1_links.err
-$SRC_H5STAT_TESTFILES/h5stat_err1_dims.err
-$SRC_H5STAT_TESTFILES/h5stat_err1_numattrs.err
-$SRC_H5STAT_TESTFILES/h5stat_err2_numattrs.err
-$SRC_H5STAT_TESTFILES/h5stat_notexist.err
-$SRC_H5STAT_TESTFILES/h5stat_nofile.err
-"
-
 LIST_OTHER_TEST_FILES="
-$SRC_H5STAT_TESTFILES/h5stat_err_refcount.ddl
-$SRC_H5STAT_TESTFILES/h5stat_err_old_layout.ddl
-$SRC_H5STAT_TESTFILES/h5stat_err_old_fill.ddl
-$SRC_H5STAT_TESTFILES/h5stat_help1.ddl
-$SRC_H5STAT_TESTFILES/h5stat_help2.ddl
-$SRC_H5STAT_TESTFILES/h5stat_notexist.ddl
-$SRC_H5STAT_TESTFILES/h5stat_nofile.ddl
-$SRC_H5STAT_TESTFILES/h5stat_filters.ddl
-$SRC_H5STAT_TESTFILES/h5stat_filters-file.ddl
-$SRC_H5STAT_TESTFILES/h5stat_filters-F.ddl
-$SRC_H5STAT_TESTFILES/h5stat_filters-d.ddl
-$SRC_H5STAT_TESTFILES/h5stat_filters-g.ddl
-$SRC_H5STAT_TESTFILES/h5stat_filters-dT.ddl
-$SRC_H5STAT_TESTFILES/h5stat_filters-UD.ddl
-$SRC_H5STAT_TESTFILES/h5stat_filters-UT.ddl
-$SRC_H5STAT_TESTFILES/h5stat_tsohm.ddl
-$SRC_H5STAT_TESTFILES/h5stat_newgrat.ddl
-$SRC_H5STAT_TESTFILES/h5stat_newgrat-UG.ddl
-$SRC_H5STAT_TESTFILES/h5stat_newgrat-UA.ddl
-$SRC_H5STAT_TESTFILES/h5stat_idx.ddl
-$SRC_H5STAT_TESTFILES/h5stat_links1.ddl
-$SRC_H5STAT_TESTFILES/h5stat_links2.ddl
-$SRC_H5STAT_TESTFILES/h5stat_links3.ddl
-$SRC_H5STAT_TESTFILES/h5stat_links4.ddl
-$SRC_H5STAT_TESTFILES/h5stat_links5.ddl
-$SRC_H5STAT_TESTFILES/h5stat_dims1.ddl
-$SRC_H5STAT_TESTFILES/h5stat_dims2.ddl
-$SRC_H5STAT_TESTFILES/h5stat_numattrs1.ddl
-$SRC_H5STAT_TESTFILES/h5stat_numattrs2.ddl
-$SRC_H5STAT_TESTFILES/h5stat_numattrs3.ddl
-$SRC_H5STAT_TESTFILES/h5stat_numattrs4.ddl
+$SRC_H5STAT_OUTFILES/h5stat_err_refcount.ddl
+$SRC_H5STAT_OUTFILES/h5stat_err_old_layout.ddl
+$SRC_H5STAT_OUTFILES/h5stat_err_old_fill.ddl
+$SRC_H5STAT_OUTFILES/h5stat_help1.ddl
+$SRC_H5STAT_OUTFILES/h5stat_help2.ddl
+$SRC_H5STAT_OUTFILES/h5stat_notexist.ddl
+$SRC_H5STAT_OUTFILES/h5stat_nofile.ddl
+$SRC_H5STAT_OUTFILES/h5stat_filters.ddl
+$SRC_H5STAT_OUTFILES/h5stat_filters-cache.ddl
+$SRC_H5STAT_OUTFILES/h5stat_filters-file.ddl
+$SRC_H5STAT_OUTFILES/h5stat_filters-F.ddl
+$SRC_H5STAT_OUTFILES/h5stat_filters-d.ddl
+$SRC_H5STAT_OUTFILES/h5stat_filters-g.ddl
+$SRC_H5STAT_OUTFILES/h5stat_filters-dT.ddl
+$SRC_H5STAT_OUTFILES/h5stat_filters-UD.ddl
+$SRC_H5STAT_OUTFILES/h5stat_filters-UT.ddl
+$SRC_H5STAT_OUTFILES/h5stat_tsohm.ddl
+$SRC_H5STAT_OUTFILES/h5stat_newgrat.ddl
+$SRC_H5STAT_OUTFILES/h5stat_newgrat-UG.ddl
+$SRC_H5STAT_OUTFILES/h5stat_newgrat-UA.ddl
+$SRC_H5STAT_OUTFILES/h5stat_idx.ddl
+$SRC_H5STAT_OUTFILES/h5stat_links1.ddl
+$SRC_H5STAT_OUTFILES/h5stat_links2.ddl
+$SRC_H5STAT_OUTFILES/h5stat_links3.ddl
+$SRC_H5STAT_OUTFILES/h5stat_links4.ddl
+$SRC_H5STAT_OUTFILES/h5stat_links5.ddl
+$SRC_H5STAT_OUTFILES/h5stat_dims1.ddl
+$SRC_H5STAT_OUTFILES/h5stat_dims2.ddl
+$SRC_H5STAT_OUTFILES/h5stat_numattrs1.ddl
+$SRC_H5STAT_OUTFILES/h5stat_numattrs2.ddl
+$SRC_H5STAT_OUTFILES/h5stat_numattrs3.ddl
+$SRC_H5STAT_OUTFILES/h5stat_numattrs4.ddl
 "
 
 #
 # copy test files and expected output files from source dirs to test dir
 #
-COPY_TESTFILES="$LIST_HDF5_TEST_FILES $LIST_ERR_TEST_FILES $LIST_OTHER_TEST_FILES"
+COPY_TESTFILES="$LIST_HDF5_TEST_FILES $LIST_OTHER_TEST_FILES"
 
 COPY_TESTFILES_TO_TESTDIR()
 {
@@ -187,7 +177,6 @@ TESTING() {
 #
 TOOLTEST() {
    expect="$TESTDIR/$1"
-   expect_err="$TESTDIR/`basename $1 .ddl`.err"
    actual="$TESTDIR/`basename $1 .ddl`.out"
    actual_err="$TESTDIR/`basename $1 .ddl`.out.err"
    actual_sav=${actual}-sav
@@ -207,17 +196,7 @@ TOOLTEST() {
    cp $actual_err $actual_err_sav
    STDERR_FILTER $actual_err
 
-   if [ ! -f $expect ]; then
-      # Compare error files if the expect file doesn't exist.
-      if $CMP $expect_err $actual_err; then
-         echo " PASSED"
-      else
-         echo "*FAILED*"
-         echo "    Expected result (*.err) differs from actual result (*.out.err)"
-         nerrors="`expr $nerrors + 1`"
-         test yes = "$verbose" && $DIFF $expect_err $actual_err |sed 's/^/    /'
-      fi
-   elif $CMP $expect $actual; then
+   if $CMP $expect $actual; then
       echo " PASSED"
    else
       echo "*FAILED*"
@@ -232,6 +211,52 @@ TOOLTEST() {
    fi
 }
 
+
+# Call the h5stat tool and grep for a value
+# txttype ERRTXT greps test error output, otherwise greps test output
+GREPTEST()
+{
+    txttype=$1
+    expectdata=$2
+    expect="$TESTDIR/$3"
+    actual="$TESTDIR/`basename $1 .ddl`.out"
+    actual_err="$TESTDIR/`basename $1 .ddl`.out.err"
+    shift
+    shift
+    shift
+    if [ "$1" = -i ]; then
+        inputfile=$2
+    fi
+
+    if [ "$3" = -o ]; then
+        outputfile=$4
+    fi
+
+   TESTING $STAT $@
+   (
+      cd $TESTDIR
+      $RUNSERIAL $STAT_BIN $@
+   ) >$actual 2>$actual_err
+    RET=$?
+
+    if [ "$txttype" = "ERRTXT" ]; then
+        $GREP "$expectdata" $actual_err > /dev/null
+    else
+        $GREP "$expectdata" $actual > /dev/null
+    fi
+
+    if [ $? -eq 0 ]; then
+        echo " PASSED"
+    else
+        echo " FAILED"
+        nerrors="`expr $nerrors + 1`"
+    fi
+
+    # Clean up output file
+    if test -z "$HDF5_NOCLEANUP"; then
+        rm -f $actual $actual_err
+    fi
+}
 
 # Print a "SKIP" message
 SKIP() {
@@ -256,7 +281,7 @@ TOOLTEST h5stat_help2.ddl --help
 TOOLTEST h5stat_notexist.ddl notexist.h5
 TOOLTEST h5stat_nofile.ddl ''
 
-# Test file with groups, compressed datasets, user-applied fileters, etc.
+# Test file with groups, compressed datasets, user-applied filters, etc.
 # h5stat_filters.h5 is a copy of ../../testfiles/tfilters.h5 as of release 1.8.0-alpha4
 TOOLTEST h5stat_filters.ddl h5stat_filters.h5
 TOOLTEST h5stat_filters-file.ddl  -f   h5stat_filters.h5
@@ -266,6 +291,8 @@ TOOLTEST h5stat_filters-g.ddl  -g   h5stat_filters.h5
 TOOLTEST h5stat_filters-dT.ddl -dT  h5stat_filters.h5
 TOOLTEST h5stat_filters-UD.ddl -D h5stat_filters.h5
 TOOLTEST h5stat_filters-UT.ddl -T h5stat_filters.h5
+# Test for page buffer cache size option
+TOOLTEST h5stat_filters-cache.ddl --page-buffer-size=8192 h5stat_filters.h5
 #
 # h5stat_tsohm.h5 is a copy of ../../../test/tsohm.h5 generated by tsohm.c
 # as of release 1.8.7-snap0 (on a 64-bit machine)
@@ -282,7 +309,7 @@ TOOLTEST h5stat_idx.ddl h5stat_idx.h5
 #     -g -l 8
 #     --links=8
 #     --links=20 -g
-TOOLTEST h5stat_err1_links.ddl -l 0 h5stat_threshold.h5
+GREPTEST ERRTXT "Invalid threshold for small groups" h5stat_err1_links.ddl -l 0 h5stat_threshold.h5
 TOOLTEST h5stat_links1.ddl -g -l 8 h5stat_threshold.h5
 TOOLTEST h5stat_links2.ddl --links=8 h5stat_threshold.h5
 TOOLTEST h5stat_links3.ddl --links=20 -g h5stat_threshold.h5
@@ -297,7 +324,7 @@ TOOLTEST h5stat_links5.ddl -g -l 40000 h5stat_newgrat.h5
 #     -d --dims=-1 (incorrect threshold value)
 #     -gd -m 5
 #     -d --di=15
-TOOLTEST h5stat_err1_dims.ddl -d --dims=-1 h5stat_threshold.h5
+GREPTEST ERRTXT "Invalid threshold for small datasets" h5stat_err1_dims.ddl -d --dims=-1 h5stat_threshold.h5
 TOOLTEST h5stat_dims1.ddl -gd -m 5 h5stat_threshold.h5
 TOOLTEST h5stat_dims2.ddl -d --dims=15 h5stat_threshold.h5
 #
@@ -307,8 +334,8 @@ TOOLTEST h5stat_dims2.ddl -d --dims=15 h5stat_threshold.h5
 #    -AS -a 10
 #    -a 1
 #    -A --numattrs=25
-TOOLTEST h5stat_err1_numattrs.ddl -a -2 h5stat_threshold.h5
-TOOLTEST h5stat_err2_numattrs.ddl --numattrs h5stat_threshold.h5
+GREPTEST ERRTXT "Invalid threshold for small # of attributes" h5stat_err1_numattrs.ddl -a -2 h5stat_threshold.h5
+GREPTEST ERRTXT "Invalid threshold for small # of attributes" h5stat_err2_numattrs.ddl --numattrs h5stat_threshold.h5
 TOOLTEST h5stat_numattrs1.ddl -AS -a 10 h5stat_threshold.h5
 TOOLTEST h5stat_numattrs2.ddl -a 1 h5stat_threshold.h5
 TOOLTEST h5stat_numattrs3.ddl -A --numattrs=25 h5stat_threshold.h5
